<head>
<style>
<h1> {color: green; TEXT-DECORATION: UNDERLINE;}</h1>
<h2> {color: green; TEXT-DECORATION: UNDERLINE;}</h2>
<h3> (color: green; TEXT-DECORATION: UNDERLINE;}</h3>
</style>
</head>

theme: jekyll-theme-leap-day